# Generated by Django 4.2.7 on 2023-12-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_integration', '0003_alter_order_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
