# Generated by Django 4.2.7 on 2023-12-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_integration', '0006_order_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount_sum_notified',
            field=models.BooleanField(default=False),
        ),
    ]
