# Generated by Django 4.2.7 on 2023-12-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_integration', '0008_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
