# Generated by Django 4.2.7 on 2023-12-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_integration', '0010_order_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_item',
        ),
    ]
