# Generated by Django 4.2.7 on 2023-12-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_integration', '0013_alter_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
