# Generated by Django 4.2.7 on 2023-12-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_integration', '0015_product_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
