# Generated by Django 4.2.7 on 2023-12-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_integration', '0018_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
